### ISSUE TITLE
[Feature] share art

### ISSUE THREAD

**Issue by altair984** [TaureHorn/FoundryVTT_ActiveCharacterPortrait#8]
Part 1
Would it be too much to ask, to add a button where you can directly show the actor's portrait to your players if you are the Dungeon master?

Part 2 
Would it be too much to ask that the image stays in the center of the screen and that the player can't close the image until the master removes it, to make focus as if the actor was talking to the others?

example:

![image](https://github.com/TaureHorn/FoundryVTT_ActiveCharacterPortrait/assets/52784850/31cb8e30-3885-4930-94a4-7c998d12fe64)

**Comment by TaureHorn** [comment]
#9 Added a button on the GM's portrait window to show to players and added an extension to the foundry inbuilt ImagePopout app window so that it obeys the same close behaviour as the main portrait

#10 Changed the default window behaviour for this modules windows to bypass the Esc key. Can change back to close on 'Esc' in the settings if you wish.

Update to v1.3.0 to access changes and you should be golden :+1:
